Sprint1
ClevertecFrontendLab/sprint1-radomir-radionov pull request #1
Opened 2023-01-23 17:39 UTC by radomir-radionov

2023-01-23 18:48 UTC, Ivan6813 requested changes

2023-01-23 18:48 UTC, Ivan6813 commented on src/routes/AppRouter.tsx
> +
Проверь как у тебя отображаются книги. При смене вида отображения ничего не меняется + что-то не вижу на скриншотах страницу с выбранной книгой.
![msedge_xQOW725eso](https://user-images.githubusercontent.com/79784960/214123519-0c20c4ad-dc6c-4f44-b102-2125cda0f5da.png)
![msedge_ZzvD7RlnYU](https://user-images.githubusercontent.com/79784960/214123558-3550db42-6ecd-4977-8c9a-2423a71b3e6d.png)

2023-01-23 18:59 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674500355/book-page%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674500355/book-page%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674500355/book-page.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674500355/content-list%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674500355/content-list%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674500355/content-list.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674500355/content-window%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674500355/content-window%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674500355/content-window.png)

2023-01-23 22:10 UTC, klichkovskiy requested changes
Доработать переход на страницу книги

2023-01-23 22:10 UTC, klichkovskiy commented on src/routes/AppRouter.tsx
> +        </Route>
При клике на книгу не происходит роутинга на страницу книги

2023-01-23 22:15 UTC, radomir-radionov commented on src/routes/AppRouter.tsx
> +        </Route>
![image](https://user-images.githubusercontent.com/66359081/214162094-f1cf0778-ac72-4b6d-83c4-4b0e710bdcc2.png)
Нажмите на название книги, там  ховер есть название  загоарется оранжевым, кликаете и переходите!

2023-01-23 22:17 UTC, radomir-radionov commented on src/routes/AppRouter.tsx
> +        </Route>
Работает идеально, кликните на название книги и появится страница книги и маршрут  изменится в роутере.

2023-01-23 22:21 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674512463/book-page%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674512463/book-page%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674512463/book-page.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674512463/content-list%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674512463/content-list%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674512463/content-list.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674512463/content-window%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674512463/content-window%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674512463/content-window.png)

2023-01-23 22:22 UTC, radomir-radionov commented
Кликните на имя карточки и вас роутер перенесёт и мои предыдущие сообщения.

2023-01-23 22:51 UTC, ValadzkoAliaksei requested changes

2023-01-23 22:51 UTC, ValadzkoAliaksei commented on src/modules/BooksList/BookItemShort/BookItemShort.tsx
> +    <BookItemStyled data-test-id='card'>
На сколько я помню, то по клику на карточку книги должен быть переход на страницу книги по id
У вас судя по скриншотам данного функционала нет или оно не работает должным образом (нет скриншота страницы книги)

2023-01-23 22:51 UTC, ValadzkoAliaksei commented on src/routes/AppRouter.tsx
> +        </Route>
согласно заданию, необходимо кликать не на название книги, а на всю картоxчку книги ( на которую у вас весит data-test-id) 
Заранее спасибо)

2023-01-23 23:15 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674515724/book-page%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674515724/book-page%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674515724/book-page.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674515724/content-list%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674515724/content-list%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674515724/content-list.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674515724/content-window%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674515724/content-window%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674515724/content-window.png)

2023-01-23 23:17 UTC, radomir-radionov commented
Есть скрины отдельной страницы, я добавил переход по клику на компонент с тестом

2023-01-23 23:37 UTC, ValadzkoAliaksei approved these changes

2023-01-24 00:04 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674518699/book-page%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674518699/book-page%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674518699/book-page.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674518699/content-list%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674518699/content-list%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674518699/content-list.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674518699/content-window%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674518699/content-window%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1674518699/content-window.png)

2023-01-24 06:08 UTC, Ivan6813 approved these changes

2023-01-24 07:18 UTC, SergeyGlazun approved these changes

2023-01-24 08:29 UTC, klichkovskiy approved these changes

2023-01-24 08:35 UTC, merged